{{- with $.Values }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grw.fullname" $ }}
  namespace: {{ include "grw.namespace" $ }}
  labels:
    {{- include "grw.labels" $ | nindent 4 }}
  {{- if (or .commonAnnotations .config.reloaderAnnotation) }}
  annotations:
    {{- if .config.reloaderAnnotation }}
    reloader.stakater.com/auto: 'true'
    {{- end }}
    {{- with .commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      {{- include "grw.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "grw.selectorLabels" $ | nindent 8 }}
        {{- with .podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") $ | sha256sum }}
        {{- if (not .config.existingSecret) }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") $ | sha256sum }}
        {{- end }}
        {{- with .podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 10Mi

      containers:
        - name: gitlab-redmine-webhook
          image: {{ include "grw.image" $ }}
          imagePullPolicy: {{ .image.pullPolicy }}

          envFrom:
            - configMapRef:
                name: {{ include "grw.fullname" $ }}
            - secretRef:
              {{- if .config.existingSecret }}
                name: {{ .config.existingSecret }}
              {{- else }}
                name: {{ include "grw.fullname" $ }}
              {{- end }}

          ports:
            - containerPort: 8000
              name: http
              protocol: TCP

          resources:
            {{- toYaml .resources | nindent 12}}

          volumeMounts:
            - name: tmp
              mountPath: /tmp

          startupProbe:
            httpGet:
              path: /health
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000

          securityContext:
            {{- toYaml .containerSecurityContext | nindent 12 }}

      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}

      serviceAccountName: {{ include "grw.serviceAccountName" $ }}
{{- end }}
