---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grw.fullname" $ }}
  namespace: {{ include "grw.namespace" $ }}
  labels:
    {{- include "grw.labels" $ | nindent 4 }}
  {{- with .commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "grw.selectorLabels" $ | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 8000
