# ---
# name: Build and Push

# on:
#   push:
#     tags: ['v*']

# jobs:
#   build-push:
#     runs-on: ubuntu-latest

#     env:
#       REGISTRY: ghcr.io/${{ github.repository_owner }}
#       IMAGE_NAME: gitlab-redmine-webhook

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Build
#         uses: redhat-actions/buildah-build@v2
#         with:
#           image: ${{ env.IMAGE_NAME }}
#           tags: latest ${{ github.ref }}
#           containerfiles: |
#             ./Containerfile

#       - name: Login to GitHub Container Registry
#         uses: redhat-actions/podman-login@v1
#         with:
#           registry: ${{ env.REGISTRY }}
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       - name: Build and push Container image to GitHub Container Registry
#         uses: redhat-actions/push-to-registry@v2
#         with:
#           image: ${{ steps.build-image.outputs.image }}
#           tags: ${{ steps.build-image.outputs.tags }}
#           registry: ${{ env.REGISTRY }}
