---
name: Release Helm Chart

on:
  push:
    tags: ['helm-v*']

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CHANGELOG_FILE: helm-chart/CHANGELOG.md

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Parse version
        run: echo "VERSION=$(echo $GITHUB_REF | sed -E 's;^refs/tags/helm-v;;')" >> $GITHUB_ENV

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.19.2

      - name: Package and push Helm Chart
        run: .github/helm-package-push.sh
        env:
          HELM_USERNAME: ${{ github.actor }}
          HELM_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate release notes
        run: .github/gen-release-notes.sh
        env:
          # yamllint disable rule:line-length
          RELEASE_NOTES_PRE: |-
            ## Helm Chart
            `oci://ghcr.io/${{github.repository_owner}}/helm/gitlab-redmine-webhook --version ${{env.VERSION}}`

            ## Chart README
            https://github.com/${{github.repository_owner}}/blob/helm-v${{env.VERSION}}/helm-chart/README.md
          # yamllint enable rule:line-length

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body_path: .github/release_notes.md
          make_latest: false
