---
name: Release

on:
  push:
    tags: ['v*']

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CT_REGISTRY: ghcr.io/${{ github.repository_owner }}
      CT_IMAGE_NAME: gitlab-redmine-webhook
      CHANGELOG_FILE: CHANGELOG.md
      RELEASE_NOTES_PRE: |-
        ## Container image
        `ghcr.io/${GITHUB_REPOSITORY}:v${VERSION}`


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Parse version
        run: echo "VERSION=$(echo $GITHUB_REF | sed -E 's;^refs/tags/v;;')" >> $GITHUB_ENV

      - name: Build
        uses: redhat-actions/buildah-build@v2
        id: build-image
        with:
          image: ${{ env.CT_IMAGE_NAME }}
          tags: latest v${{ env.VERSION }}
          containerfiles: |
            ./Containerfile

      - name: Login to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.CT_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Container image to GitHub Container Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.CT_REGISTRY }}

      - name: Generate release notes
        run: .github/gen-release-notes.sh

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body_path: .github/release_notes.md
